version: "3"

services:
  asf-claim:
    build: .
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      # - ASF_PORT=1242
      # - ASF_HOST=localhost
      # - ASF_PASSWORD=hunter2
      # - ASF_COMMAND_PREFIX=!
      # - ASF_HTTPS=false
      # - ASF_BOTS=asf #https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Commands#bots-argument
